[book]
title = "buildyourownlisp-in-zig"
description = "buildyourownlisp in zig"
language = "ko"
src = "src"

[output.html]
no-section-label = true
site-url = "/buildyourownlisp-in-zig/"
git-repository-url = "https://github.com/netpyoung/buildyourownlisp-in-zig"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/netpyoung/buildyourownlisp-in-zig/edit/main/{path}"

additional-css = ["theme/css/custom.css"]